baseurl = "/"
languageCode = "en-us"
theme = "paper-new"
paginate = 5

[params]
  # color style
  color = 'light'                           # linen, wheat, gray, light

  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true                               # enable KaTex math typesetting globally

  # header social icons
  github = 'JulienHeiduk'                 # github.com/YOUR_GITHUB_ID
  linkedin = 'julien-heiduk'             # linkedin.com/in/YOUR_LINKEDIN_ID

  avatar = 'https://gravatar.com/julienheiduk'                 # gravatar email or image url
  name = 'Julien Heiduk'
  bio = "Let's talk about recommender systems and ML in productions!"
  
[languages]
  [languages.en]
    languageName = "English"
    title = "Julien Heiduk"
    subtitle = "A simple blog about data..."
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "JHeiduk.com"
      logoHomeLink = "/"

#    [languages.en.menu]
#      [[languages.en.menu.main]]
#        identifier = "about"
#        name = "About"
#        url = "/about"

